# -*- coding: utf-8 -*-
"""Lepi App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vlcb5XXA4qiQrGKUVglgV0bYnG4jSnDt
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import os
import pandas as pd # Import pandas for data logging and table display
import datetime # Import datetime for timestamps
import base64 # Import base64 for background image utility

# --- Utility Function for Background Image ---
def _get_base64_image(image_path):
    """Helper to convert local image to base64 for CSS background."""
    import base64
    with open(image_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()

def set_background_image(image_path):
    """Sets a background image for the Streamlit application using CSS."""
    st.markdown(
        f"""
        <style>
        .stApp {{
            background-image: url("data:image/jpeg;base64,{_get_base64_image(image_path)}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
        }}
        </style>
        """,
        unsafe_allow_html=True
    )

# --- Configuration and Model Loading ---

# Define the directory where your models are stored
MODEL_DIR = './model' # Assuming models are in a 'model' subdirectory
IMAGE_SIZE = (180, 180) # Model's expected input size

# Ensure the model directory exists
if not os.path.exists(MODEL_DIR):
    # This prevents the app from running if models are missing, making the file smaller
    # For execution in a constrained environment, this error message is helpful.
    pass

# Ensure the data directory exists for logging
DATA_DIR = './Data'
os.makedirs(DATA_DIR, exist_ok=True)


# --- Apply the background image and general styles ---
# Apply the background image (assuming it exists)
try:
    # IMPORTANT: Ensure 'icon/bgbutterfly.jpg' exists in your execution environment
    set_background_image('icon/bg.jpg')
except FileNotFoundError:
    # Fallback or warning if the image file is missing
    pass

# --- Glasmorphism CSS ---
# Define general styles for glasmorphism elements within the app
st.markdown(
    """
    <style>
    /* General body/text styling for better readability on blurred backgrounds */
    body {
        color: #333333; /* Darker text for better contrast */
    }
    h1, h2, h3, h4, h5, h6 {
        color: #222222;
        text-shadow: 1px 1px 2px rgba(0,0,0,0.1); /* Subtle text shadow */
    }
    .stTextInput label, .stSelectbox label, .stRadio label, .stFileUploader label, .stCameraInput label {
        color: #333333;
        font-weight: bold;
    }
    .stButton>button {
        background-color: rgba(255, 255, 255, 0.2);
        border: 1px solid rgba(255, 255, 255, 0.3);
        color: #333333;
        transition: all 0.3s ease;
        border-radius: 8px; /* Rounded buttons */
    }
    .stButton>button:hover {
        background-color: rgba(255, 255, 255, 0.3);
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    }

    /* Apply glasmorphism to the main content area */
    .main .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
        padding-left: 1rem;
        padding-right: 1rem;
        border-radius: 16px;
        background: rgba(255, 255, 255, 0.15); /* Slightly less opaque for the whole main area */
        backdrop-filter: blur(8px);
        -webkit-backdrop-filter: blur(8px);
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.2);
        margin-bottom: 20px;
    }

    /* Apply glasmorphism to the sidebar */
    .css-pkaj6s { /* Common class for the sidebar parent div */
        background: rgba(255, 255, 255, 0.15);
        backdrop-filter: blur(8px);
        -webkit-backdrop-filter: blur(8px);
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        border: 1px solid rgba(255, 255, 255, 0.2);
        border-radius: 16px;
        padding: 20px;
        margin-right: 10px;
    }

    /* Specific glasmorphism container for individual elements like the prediction card */
    .glasmorphism-card {
        background: rgba(255, 255, 255, 0.25); /* Slightly more opaque for inner cards */
        border-radius: 12px;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.4);
        padding: 15px;
        margin-bottom: 15px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# --- Load Models (once) ---
@st.cache_resource
def load_model(model_name):
    model_path = os.path.join(MODEL_DIR, model_name)
    if not os.path.exists(model_path):
        # Allow the app to run without models for the table display if needed
        return None
    try:
        # Suppress potential warnings during model loading in a Streamlit context
        model = tf.keras.models.load_model(model_path, compile=False)
        return model
    except Exception:
        # st.error(f"Error loading {model_name} Model: {e}")
        return None

# Load all models at the start
butterfly_species_model = load_model('model_Butterfly_Species.h5')
lifestages_model = load_model('model_Life_Stages.h5')
pupaedefects_model = load_model('model_Pupae_Defects.h5')
larvaldiseases_model = load_model('model_Larval_Diseases.h5')

# Check if at least one model failed to load
MODELS_LOADED = any([
    butterfly_species_model, lifestages_model,
    pupaedefects_model, larvaldiseases_model
])

# --- Define Class Names and Associated Information for Each Model (UPDATED) ---

BUTTERFLY_SPECIES_INFO = {
    "Butterfly-Clippers": {
        "scientific_name": "Parthenos sylvia",
        "family": "Nymphalidae",
        "discovered": "Carl Peter Thunberg, Cramer",
        "year": "1776",
        "description": "Forewing triangular; costa very slightly curved, apex rounded, exterior margin oblique and slightly scalloped, posterior margin short, angle convex",
        "habitat": "Tropical rainforests, secondary forests",
        "wingspan": "80-90mm",
        "conservation_status": "Stable",
        "distribution": "Southeast Asia, Indonesia, Malaysia",
        'plant': ['Ixora', 'Wild Cucumber', 'Passiflora'],
        'dailyConsumption': 120
    },
    "Butterfly-Common Jay": {
        "scientific_name": "Graphium doson",
        "family": "Papilionidae",
        "discovered": "C. & R. Felder",
        "year": "1864",
        "description": "Medium-sized swallowtail with distinctive blue-green markings and tail extensions",
        "habitat": "Forest edges, gardens, parks",
        "wingspan": "70-85mm",
        "conservation_status": "Stable",
        "distribution": "India, Southeast Asia, Southern China",
        'plant': ['Avocado Tree', 'Soursop', 'Sugar Apple', 'Amuyon', 'Indian Tree'],
        'dailyConsumption': 160
    },
    "Butterfly-Common Lime": {
        "scientific_name": "Papilio demoleus",
        "family": "Papilionidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "The butterfly is tailless and has a wingspan 80–100 mm, the butterfly has a large number of irregular spots on the wing",
        "habitat": "Gardens, citrus groves, urban areas",
        "wingspan": "80-100mm",
        "conservation_status": "Stable",
        "distribution": "Asia, introduced to Caribbean and parts of America",
        'plant': ['Limeberry', 'Calamondin', 'Pomelo', 'Sweet Orange', 'Calamansi'],
        'dailyConsumption': 140
    },
    "Butterfly-Common Mime": {
        "scientific_name": "Papilio clytia",
        "family": "Papilionidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "It's a black-bodied swallowtail and a good example of Batesian mimicry, meaning it mimics the appearance of other distasteful butterflies",
        "habitat": "Forest areas, woodland edges",
        "wingspan": "85-95mm",
        "conservation_status": "Stable",
        "distribution": "India, Southeast Asia",
        'plant': ['Clover Cinnamon', 'Wild Cinnamon', 'Aristolochia'],
        'dailyConsumption': 150
    },
    "Butterfly-Common Mormon": {
        "scientific_name": "Papilio polytes",
        "family": "Papilionidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "Large black swallowtail with sexual dimorphism, females often mimic other species",
        "habitat": "Gardens, forest edges, agricultural areas",
        "wingspan": "90-110mm",
        "conservation_status": "Stable",
        "distribution": "India, Southeast Asia, Southern China",
        'plant': ['Limeberry', 'Calamondin', 'Pomelo', 'Sweet Orange', 'Calamansi', 'Lemoncito'],
        'dailyConsumption': 155
    },
    "Butterfly-Emerald Swallowtail": {
        "scientific_name": "Papilio palinurus",
        "family": "Papilionidae",
        "discovered": "Fabricius",
        "year": "1787",
        "description": "Stunning black butterfly with brilliant emerald green bands and patches",
        "habitat": "Primary and secondary rainforests",
        "wingspan": "80-100mm",
        "conservation_status": "Vulnerable",
        "distribution": "Southeast Asia, Indonesia, Philippines",
        'plant': ['Curry Leafs', 'Pink Lime-Berry Tree', 'Glycosmis'],
        'dailyConsumption': 180
    },
    "BUtterfly-Golden Birdwing": {
        "scientific_name": "Troides rhadamantus",
        "family": "Papilionidae",
        "discovered": "H. Lucas",
        "year": "1835",
        "description": "Large golden yellow and black birdwing butterfly, one of the largest in the world",
        "habitat": "Primary rainforests, high canopy",
        "wingspan": "150-180mm",
        "conservation_status": "Protected",
        "distribution": "Philippines (endemic)",
        'plant': ['Dutchman pipe', 'Indian Birthwort', 'Aristolochia'],
        'dailyConsumption': 200
    },
    "Butterfly-Gray Glassy Tiger": {
        "scientific_name": "Ideopsis juventa",
        "family": "Nymphalidae",
        "discovered": "Cramer",
        "year": "1777",
        "description": "Semi-transparent wings with gray and white markings, slow graceful flight",
        "habitat": "Forest clearings, edges, gardens",
        "wingspan": "70-85mm",
        "conservation_status": "Stable",
        "distribution": "Southeast Asia, Indonesia",
        'plant': ['Parsonsia', 'Tylophora', 'Asclepias'],
        'dailyConsumption': 130
    },
    "Butterfly-Great Eggfly": {
        "scientific_name": "Hypolimnas bolina",
        "family": "Nymphalidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "Large butterfly with striking sexual dimorphism, males are black with white patches",
        "habitat": "Gardens, forest edges, open areas",
        "wingspan": "85-100mm",
        "conservation_status": "Stable",
        "distribution": "Indo-Pacific region, Australia",
        'plant': ['Portulaca', 'Synedrella', 'Asystasia'],
        'dailyConsumption': 145
    },
    "Butterfly-Great Yellow Mormon": {
        "scientific_name": "Papilio lowi",
        "family": "Papilionidae",
        "discovered": "Druce",
        "year": "1873",
        "description": "Large yellow and black swallowtail with distinctive wing patterns",
        "habitat": "Primary forests, mountainous regions",
        "wingspan": "120-140mm",
        "conservation_status": "Near Threatened",
        "distribution": "Borneo (endemic)",
        'plant': ['Citrus species', 'Murraya', 'Glycosmis'],
        'dailyConsumption': 175
    },
    "Butterfly-Paper Kite": {
        "scientific_name": "Idea leuconoe",
        "family": "Nymphalidae",
        "discovered": "Erichson",
        "year": "1834",
        "description": "Large white butterfly with black markings and semi-transparent wings",
        "habitat": "Mangroves, coastal forests, gardens",
        "wingspan": "95-110mm",
        "conservation_status": "Stable",
        "distribution": "Southeast Asia, Taiwan, Southern Japan",
        'plant': ['Parsonsia', 'Tylophora', 'Gymnema'],
        'dailyConsumption': 135
    },
    "Butterfly-Pink Rose": {
        "scientific_name": "Pachliopta kotzebuea",
        "family": "Papilionidae",
        "discovered": "Eschscholtz",
        "year": "1821",
        "description": "Beautiful rose swallowtail with pink and black coloration",
        "habitat": "Forest areas, gardens with host plants",
        "wingspan": "80-90mm",
        "conservation_status": "Stable",
        "distribution": "Philippines (endemic)",
        'plant': ['Aristolochia', 'Dutchman pipe', 'Birthwort'],
        'dailyConsumption': 165
    },
    "Butterfly-Plain Tiger": {
        "scientific_name": "Danaus chrysippus",
        "family": "Nymphalidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "Orange butterfly with black borders and white spots, toxic to predators",
        "habitat": "Open areas, gardens, grasslands",
        "wingspan": "70-80mm",
        "conservation_status": "Stable",
        "distribution": "Africa, Asia, Australia",
        'plant': ['Calotropis', 'Asclepias', 'Crown flower'],
        'dailyConsumption': 125
    },
    "Butterfly-Red Lacewing": {
        "scientific_name": "Cethosia biblis",
        "family": "Nymphalidae",
        "discovered": "Drury",
        "year": "1773",
        "description": "Stunning red and black butterfly with intricate lacewing patterns",
        "habitat": "Primary rainforests, shaded areas",
        "wingspan": "80-90mm",
        "conservation_status": "Vulnerable",
        "distribution": "India, Southeast Asia",
        'plant': ['Passiflora', 'Adenia', 'Passion vine'],
        'dailyConsumption': 170
    },
    "Butterfly-Scarlet Mormon": {
        "scientific_name": "Papilio rumanzovia",
        "family": "Papilionidae",
        "discovered": "Eschscholtz",
        "year": "1821",
        "description": "Large black swallowtail with brilliant red markings",
        "habitat": "Primary forests, mountainous regions",
        "wingspan": "110-130mm",
        "conservation_status": "Protected",
        "distribution": "Philippines (endemic)",
        'plant': ['Limeberry', 'Calamondin', 'Pomelo', 'Sweet Orange', 'Calamansi'],
        'dailyConsumption': 185
    },
    "Butterfly-Tailed Jay": {
        "scientific_name": "Graphium agamemnon",
        "family": "Papilionidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "Green and black swallowtail with distinctive tails and spotted pattern",
        "habitat": "Gardens, forest edges, parks",
        "wingspan": "80-100mm",
        "conservation_status": "Stable",
        "distribution": "India, Southeast Asia, Australia",
        'plant': ['Polyalthia', 'Annona', 'Sugar apple', 'Amuyon','Indian tree'],
        'dailyConsumption': 155
    },
    "Moth-Atlas": {
        "scientific_name": "Attacus atlas",
        "family": "Saturniidae",
        "discovered": "Linnaeus",
        "year": "1758",
        "description": "One of the largest moths in the world with distinctive triangular wing tips",
        "habitat": "Tropical and subtropical forests",
        "wingspan": "200-280mm",
        "conservation_status": "Stable",
        "distribution": "Asia, from India to Indonesia",
        'plant': ['Rambutan', 'Willow', 'Privet', 'Tree of Heaven'],
        'dailyConsumption': 220
    },
    "Moth-Giant Silk": {
        "scientific_name": "Samia cynthia",
        "family": "Saturniidae",
        "discovered": "Drury",
        "year": "1773",
        "description": "Large silk moth with eye spots and feathery antennae",
        "habitat": "Deciduous forests, parks",
        "wingspan": "100-150mm",
        "conservation_status": "Stable",
        "distribution": "Asia, introduced to North America",
        'plant': ['Ailanthus', 'Cherry', 'Lilac', 'Privet'],
        'dailyConsumption': 190
    }
}
butterfly_species_names = list(BUTTERFLY_SPECIES_INFO.keys()) # Ensure order matches training output

lifestages_info = {
    "Butterfly": {"stages_info": "Reproductive stage, winged insect capable of flight."},
    "Eggs": {"stages_info": "Early developmental stage, typically laid on host plants."},
    "Larvae": {"stages_info": "Caterpillar stage, primary feeding and growth phase."},
    "Pupae": {"stages_info": "Chrysalis (butterfly) or cocoon (moth) stage, metamorphosis occurs."},
}
lifestages_names = list(lifestages_info.keys())

pupaedefects_info = {
    "Ant bites": {"quality_info": "Indicates ant damage, can lead to pupae death or malformation."},
    "Deformed body": {"quality_info": "Physical deformities, may indicate poor health or environmental stress."},
    "Healthy Pupae": {"quality_info": "No visible defects, good potential for adult emergence."},
    "Old Pupa": {"quality_info": "Pupae nearing emergence or past its prime, may be discolored or shriveled."},
    "Overbend": {"quality_info": "Abnormal curvature, can impede proper development."},
    "Stretch abdomen": {"quality_info": "Abdomen appears stretched or elongated, potentially due to stress or disease."},
}
pupaedefects_names = list(pupaedefects_info.keys())

larvaldiseases_info = {
    "Anaphylaxis Infection": {"treatment_info": "Seek veterinary advice; isolate infected larvae. No specific treatment for severe cases."},
    "Gnathostomiasis": {"treatment_info": "Parasitic infection. Isolate, remove parasites if visible, improve hygiene."},
    "Healthy": {"treatment_info": "Larva appears healthy with no signs of disease."},
    "Nucleopolyhedrosis": {"treatment_info": "Highly contagious viral disease. Isolate and destroy infected larvae to prevent spread. Disinfect rearing areas."},
}
larvaldiseases_names = list(larvaldiseases_info.keys())


# --- Classification Function ---
def classify_image(image_file, model, class_names, details_dict=None):
    """
    Classifies an image using the specified Keras model and class names.
    """
    if model is None:
        return None

    try:
        image = Image.open(image_file)
        img_resized = image.resize(IMAGE_SIZE)
        img_array = tf.keras.utils.img_to_array(img_resized)
        img_array = tf.expand_dims(img_array, 0) # Add batch dimension
        img_array = img_array / 255.0 # Ensure normalization if model expects it

        predictions = model.predict(img_array)
        result = tf.nn.softmax(predictions[0])
        predicted_class_index = np.argmax(result)
        predicted_score = np.max(result).item() * 100

        if predicted_class_index < len(class_names):
            predicted_class_name = class_names[predicted_class_index]
            result_data = {
                "class_name": predicted_class_name,
                "score": predicted_score,
                "index": predicted_class_index
            }
            if details_dict and predicted_class_name in details_dict:
                # Add all dictionary details to the result
                result_data.update(details_dict[predicted_class_name])
            return result_data
        else:
            return {"class_name": "Unknown Class (Index out of bounds)", "score": 0.0, "index": predicted_class_index}
    except Exception as e:
        # st.error(f"Error during image classification: {e}")
        return None

# --- Streamlit UI Layout ---
st.title("🦋 Lepi App")
st.write("Upload an image or capture from your webcam to classify butterflies, their life stages, or identify pupae defects and larval diseases.")

# Sidebar for navigation
with st.sidebar:
    st.title("Navigation")
    selected_menu_item = st.radio(
        "Select a Tool",
        ["Image Classifiers", "Species Reference Table"]
    )
    if not MODELS_LOADED:
         st.warning("Note: Models failed to load. Only the Reference Table is functional.")

# --- Reference Table Content ---
if selected_menu_item == "Species Reference Table":
    st.header("📚 Butterfly & Moth Species Reference")
    st.markdown(
        """
        <div class="glasmorphism-card">
        Explore detailed information on various butterfly and moth species, including their scientific classification, habitat, and host plants.
        </div>
        """,
        unsafe_allow_html=True
    )

    # 1. Convert the dictionary to DataFrame
    df_species = pd.DataFrame.from_dict(BUTTERFLY_SPECIES_INFO, orient='index')

    # 2. Flatten the 'plant' list for better table display
    df_species['plant'] = df_species['plant'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

    # 3. Clean up columns and rename for display
    df_species.index.name = 'Species Name'
    df_species_display = df_species.reset_index()

    # Define the desired column order and display names
    display_columns_map = {
        'Species Name': 'Species Name',
        'scientific_name': 'Scientific Name',
        'family': 'Family',
        'wingspan': 'Wingspan',
        'conservation_status': 'Status',
        'distribution': 'Distribution',
        'habitat': 'Habitat',
        'plant': 'Host Plants (Larvae)',
        'dailyConsumption': 'Daily Consumption (mg)',
        'discovered': 'Discovered By',
        'year': 'Year',
        'description': 'Description',
    }

    # Select and rename the columns
    df_species_display = df_species_display.rename(columns=display_columns_map)
    df_species_display = df_species_display[list(display_columns_map.values())]

    # 4. Display the table
    st.dataframe(
        df_species_display,
        use_container_width=True,
        hide_index=True,
        column_order=list(display_columns_map.values())
    )


# --- Image Classifiers Content ---
elif selected_menu_item == "Image Classifiers":
    st.header("🔬 Image Classifiers")
    st.write("Select a classifier to analyze your butterfly images.")

    if not MODELS_LOADED:
        st.error("Cannot run classification. Required TensorFlow/Keras models are not found or failed to load. Check the './model' directory.")
        st.stop()

    classifier_choice = st.radio(
        "Choose Classifier Type",
        ["Butterfly Species", "Life Stages", "Pupae Defects", "Larval Diseases"]
    )

    st.markdown("---")

    # Input method selection for classifiers
    input_method = st.radio("Choose an input method:", ("Upload Image", "Capture from Webcam"))

    uploaded_file = None
    camera_image = None

    if input_method == "Upload Image":
        uploaded_file = st.file_uploader(f"Upload an image for {classifier_choice} classification...", type=["jpg", "jpeg", "png"])
    elif input_method == "Capture from Webcam":
        camera_image = st.camera_input("Take a picture")

    source_image = None
    if uploaded_file is not None:
        source_image = uploaded_file
    elif camera_image is not None:
        source_image = camera_image

    if source_image is not None:
        st.image(source_image, caption='Image for Classification', use_container_width=True)
        st.write("")
        st.write("Classifying...")

        model_to_use = None
        class_names_to_use = []
        details_to_use = {}
        csv_file_path = None

        if classifier_choice == "Butterfly Species":
            model_to_use = butterfly_species_model
            class_names_to_use = butterfly_species_names
            details_to_use = BUTTERFLY_SPECIES_INFO
            csv_file_path = os.path.join(DATA_DIR, "butterfly_table_species.csv")
        elif classifier_choice == "Life Stages":
            model_to_use = lifestages_model
            class_names_to_use = lifestages_names
            details_to_use = lifestages_info
            csv_file_path = os.path.join(DATA_DIR, "stages_records.csv")
        elif classifier_choice == "Pupae Defects":
            model_to_use = pupaedefects_model
            class_names_to_use = pupaedefects_names
            details_to_use = pupaedefects_info
            csv_file_path = os.path.join(DATA_DIR, "pupae_defects_quality_info.csv")
        elif classifier_choice == "Larval Diseases":
            model_to_use = larvaldiseases_model
            class_names_to_use = larvaldiseases_names
            details_to_use = larvaldiseases_info
            csv_file_path = os.path.join(DATA_DIR, "larval_diseases_quality_records.csv")

        if model_to_use:
            classification_result = classify_image(source_image, model_to_use, class_names_to_use, details_to_use)

            if classification_result and classification_result['class_name'] != "Unknown Class (Index out of bounds)":

                # --- Result Display Card ---
                st.markdown('<div class="glasmorphism-card">', unsafe_allow_html=True)
                st.success(f"**{classifier_choice} Prediction:** **{classification_result['class_name']}** (Confidence: {classification_result['score']:.2f}%)")

                # Display detailed information
                if classifier_choice == "Butterfly Species":
                    st.subheader("Species Details")
                    st.write(f"**Scientific Name:** {classification_result.get('scientific_name', 'N/A')}")
                    st.write(f"**Family:** {classification_result.get('family', 'N/A')}")
                    st.write(f"**Wingspan:** {classification_result.get('wingspan', 'N/A')}")
                    st.write(f"**Habitat:** {classification_result.get('habitat', 'N/A')}")

                    plants = classification_result.get('plant', [])
                    if plants:
                        st.write(f"**Host Plants (Larvae):** {', '.join(plants)}")

                    st.caption(f"**Description:** {classification_result.get('description', 'N/A')}")

                elif 'stages_info' in classification_result:
                    st.write(f"Stages Info: {classification_result['stages_info']}")
                elif 'quality_info' in classification_result:
                    st.write(f"Quality Info: {classification_result['quality_info']}")
                elif 'treatment_info' in classification_result:
                    st.write(f"Treatment Info: {classification_result['treatment_info']}")

                st.markdown('</div>', unsafe_allow_html=True) # Close the custom div

                # --- Data Logging ---
                date_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                location = "Manila, Metro Manila, Philippines"

                image_filename_for_log = uploaded_file.name if uploaded_file is not None else f"webcam_capture_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"

                # Create log entry with all relevant keys
                log_entry = {
                    "classifier": classifier_choice,
                    "class_name": classification_result['class_name'],
                    "score": classification_result['score'],
                    "date_time": date_time,
                    "location": location,
                    "image_path": image_filename_for_log,
                    **{k: v if not isinstance(v, list) else ', '.join(v) for k, v in classification_result.items() if k not in ['class_name', 'score', 'index']}
                }

                df_log = pd.DataFrame([log_entry])

                # Append to CSV (or create if it doesn't exist)
                if os.path.exists(csv_file_path):
                    df_log.to_csv(csv_file_path, mode='a', header=False, index=False)
                else:
                    df_log.to_csv(csv_file_path, mode='w', header=True, index=False)

                st.success(f"Classification result logged to {csv_file_path}")

            else:
                st.error(f"Could not classify the image for {classifier_choice} or prediction was 'Unknown Class'.")
        else:
            st.warning(f"The {classifier_choice} model is not loaded. Please check the model path and ensure the model file exists.")

st.info("""
**Data Status:** The application is using a local model cache and logging results to the `./Data` directory.
""")