[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lepvision"
version = "0.1.0"
description = "Butterfly classification pipeline with Streamlit deployment"
authors = [{ name = "Jerwin", email = "your-email@example.com" }]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy>=1.24,<1.26",
    "tensorflow>=2.12",
    "jax>=0.4.13",
    "streamlit>=1.28",
    "scikit-learn",
    "pandas",
    "matplotlib",
    "Pillow",
    "opencv-python",
    "requests"
]

[tool.setuptools.packages.find]
where = ["src"]
